// src/lib/constants.ts
export const PREDEFINED_SKILLS = [
  // 🎨 Creative & Design
  "Graphic Designer",
  "Commercial Photographer",
  "Commercial Videographer",
  "Male Model",
  "Female Model",
  "Voice Over Artist",
  "UI Design",
  "UX Design",
  "Illustration",
  "Logo Design",
  "Branding",
  "Photoshop",
  "Illustrator",
  "Figma",
  "Sketch",
  "Canva",
  "Adobe XD",

  // 🎬 Media & Content
  "Video Editor",
  "Content Creator",
  "Content Writer",
  "Content Strategist",
  "Content Researcher",
  "Host / Presenter",
  "Technical Writing",
  "Blog Writing",
  "Creative Writing",
  "Editing",
  "Proofreading",
  "Translation",
  "Localization",
  "Motion Graphics",
  "Animation",
  "Premiere Pro",
  "After Effects",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Blender",
  "Audio Editing",
  "Music Production",
  "Sound Design",
  "Podcast Editing",
  "Audacity",
  "Logic Pro X",
  "Ableton Live",
  "Photography",
  "Photo Retouching",
  "Product Photography",
  "Lightroom",

  // 🌐 Development & Tech
  "Web Developer",
  "Mobile App Developer",
  "AI Agent Developer",
  "AI Automation Specialist",
  "ChatGPT Image Generation Specialist",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "PHP",
  "Laravel",
  "Ruby on Rails",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Machine Learning",
  "Data Science",
  "AI Development",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Data Analysis",
  "R Programming",
  "SQL",

  // 📈 Marketing & Sales
  "Social Media Manager",
  "Meta Ads Specialist",
  "Sales Executive",
  "Influencer Marketing Expert",
  "Talent Acquisition Scout",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Email Marketing",
  "Content Marketing",
  "PPC Advertising",
  "Sales",
  "Lead Generation",

  // Business & Admin (Keeping some from original for breadth)
  "Virtual Assistant",
  "Data Entry",
  "Project Management",
  "Business Analysis",
  "Customer Service",
  "Market Research",
  "PowerPoint",
  "Excel",
  "Word",
] as const;

export type Skill = typeof PREDEFINED_SKILLS[number];
