
// src/lib/constants.ts
export const PREDEFINED_SKILLS = [
  // 🎨 Creative & Design
  "Graphic Designer",
  "Commercial Photographer",
  "Commercial Videographer",
  "Male Model",
  "Female Model",
  "Voice Over Artist",
  "UI Design",
  "UX Design",
  "Illustration",
  "Logo Design",
  "Branding",
  "Photoshop",
  "Illustrator",
  "Figma",
  "Sketch",
  "Canva",
  "Adobe XD",

  // 🎬 Media & Content
  "Video Editor",
  "Content Creator",
  "Content Writer",
  "Content Strategist",
  "Content Researcher",
  "Host / Presenter",
  "Technical Writing",
  "Blog Writing",
  "Creative Writing",
  "Editing",
  "Proofreading",
  "Translation",
  "Localization",
  "Motion Graphics",
  "Animation",
  "Premiere Pro",
  "After Effects",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Blender",
  "Audio Editing",
  "Music Production",
  "Sound Design",
  "Podcast Editing",
  "Audacity",
  "Logic Pro X",
  "Ableton Live",
  "Photography",
  "Photo Retouching",
  "Product Photography",
  "Lightroom",

  // 🎞️ Film Making
  "Director",
  "Producer",
  "Screenwriter",
  "Cinematographer",
  "Gaffer",
  "Sound Recordist",
  "Boom Operator",
  "Production Designer",
  "Art Director (Film)",
  "Set Decorator",
  "Costume Designer (Film)",
  "Makeup Artist (Film)",
  "Hair Stylist (Film)",
  "Film Editor",
  "Colorist",
  "Visual Effects (VFX) Artist",
  "Storyboarding",
  "Drone Pilot (Film)",
  "Steadicam Operator",

  // 🧵 Fashion Designing
  "Fashion Designer",
  "Pattern Maker",
  "Seamstress / Tailor",
  "Fashion Illustrator",
  "Textile Designer",
  "Fashion Stylist",
  "Merchandiser (Fashion)",
  "Garment Technologist",
  "CAD Fashion Design (e.g., Lectra, Clo3D)",
  "Sustainable Fashion Design",
  "Accessory Design",

  // 🍳 Cooking & Culinary Arts
  "Chef",
  "Pastry Chef",
  "Baker",
  "Recipe Developer",
  "Food Stylist",
  "Caterer",
  "Menu Planning",
  "Culinary Instructor",
  "Food Blogger / Vlogger",
  "Bartender / Mixologist",
  "Dietary & Nutrition Planning",
  "Cake Decorating",

  // 🖼️ Fine Arts & Crafts
  "Painter (Fine Arts)",
  "Sculptor",
  "Illustrator (Traditional)",
  "Digital Painter",
  "Concept Artist",
  "Muralist",
  "Pottery / Ceramics Artist",
  "Jewelry Designer",
  "Calligrapher",
  "Printmaker",
  "Art Curation",
  "Art Restoration",
  "Craft Artist (e.g., knitting, macrame)",

  // 🎮 Game Development
  "Game Designer",
  "Gameplay Programmer",
  "Game Engine Programmer (Unity, Unreal)",
  "Unity Developer",
  "Unreal Engine Developer",
  "Game Artist (2D/3D)",
  "Character Artist",
  "Environment Artist",
  "Game Animator",
  "Level Designer",
  "Quest Designer",
  "Game UI/UX Designer",
  "Game Audio Designer/Composer",
  "Game Tester/QA",
  "Game Producer",
  "Technical Artist (Game)",
  "C# for Unity",
  "C++ for Unreal Engine",
  "Mobile Game Development",
  "VR/AR Game Development",

  // 🌐 Development & Tech
  "Web Developer",
  "Mobile App Developer",
  "AI Agent Developer",
  "AI Automation Specialist",
  "ChatGPT Image Generation Specialist",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "PHP",
  "Laravel",
  "Ruby on Rails",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Machine Learning",
  "Data Science",
  "AI Development",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Data Analysis",
  "R Programming",
  "SQL",

  // 📈 Marketing & Sales
  "Social Media Manager",
  "Meta Ads Specialist",
  "Sales Executive",
  "Influencer Marketing Expert",
  "Talent Acquisition Scout",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Email Marketing",
  "Content Marketing",
  "PPC Advertising",
  "Sales",
  "Lead Generation",

  // Business & Admin (Keeping some from original for breadth)
  "Virtual Assistant",
  "Data Entry",
  "Project Management",
  "Business Analysis",
  "Customer Service",
  "Market Research",
  "PowerPoint",
  "Excel",
  "Word",
] as const;

export type Skill = typeof PREDEFINED_SKILLS[number];
